### ISSUE TITLE
error: attribute 'nur' missing

### ISSUE THREAD

**Issue by idontgetoutmuch** [mpickering/graphmod-plugin#3]
```
bash-3.2$ nix-build
error: attribute 'nur' missing, at /Users/dom/graphmod-plugin/default.nix:3:20
```

**Comment by mpickering** [comment]
`NUR` needs to be installed as that is how the plugin system is distributed. I'm not sure how to make that any easier. 

https://github.com/nix-community/NUR

**Comment by idontgetoutmuch** [comment]
Thanks for the link - I didn't realise one needed this as well as installing cachix
